import AppKit
import CryptoKit
import Darwin

/// Watches the local pasteboard and reports new *local* copies.
///
/// macOS has no clipboard-change notification, so this polls `changeCount` on a
/// timer. Key safety behaviors:
///  - Reads `types` (metadata) before reading the data, so it can skip
///    concealed/transient content without ever pulling the secret out.
///  - Honors the nspasteboard.org convention that password managers use to mark
///    secrets as un-syncable.
///  - `write(_:)` records the resulting changeCount so applying a *remote* clip
///    doesn't bounce back out as a new local copy (echo-loop prevention).
final class ClipboardWatcher {
    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?

    /// Pasteboard markers we must never sync. Set by password managers
    /// (ConcealedType), one-time/ephemeral content (TransientType), and
    /// auto-generated content. Convention: https://nspasteboard.org
    private let skipTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    var onLocalCopy: ((_ snapshot: ClipSnapshot, _ hash: String) -> Void)?
    var maxBytes: Int = 5_000_000
    var isPaused: () -> Bool = { false }
    /// Which representations to capture (text is always included).
    var enabledKinds: () -> Set<ClipKind> = { Set(ClipKind.allCases) }

    init() {
        lastChangeCount = pasteboard.changeCount
    }

    func start() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.4, repeats: true) { [weak self] _ in
            self?.poll()
        }
    }

    private func poll() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        let observedChange = pasteboard.changeCount
        lastChangeCount = observedChange

        if isPaused() { return }

        // Inspect metadata first — do NOT read the data if it's marked secret.
        let typeNames = Set((pasteboard.types ?? []).map { $0.rawValue })
        if !skipTypes.isDisjoint(with: typeNames) { return }

        // Read any copied file URLs up front. A file copy (Finder etc.) also
        // puts the file's *name* on the pasteboard as plain text — we must NOT
        // treat that as a text clip, or a copied file (even one too big to sync)
        // shows up in history as its filename. So when this is a file copy, we
        // capture files only, never the accompanying text.
        let fileURLs = ((pasteboard.readObjects(forClasses: [NSURL.self],
                        options: [.urlReadingFileURLsOnly: true]) as? [URL]) ?? [])
                        .filter { $0.isFileURL }
        let isFileCopy = !fileURLs.isEmpty

        let kinds = enabledKinds().union([.text])   // text always considered
        var parts: [ClipKind: Data] = [:]
        if !isFileCopy {
            for kind in kinds {
                if kind == .text {
                    if let s = pasteboard.string(forType: .string), !s.isEmpty {
                        parts[.text] = Data(s.utf8)
                    }
                } else if let d = pasteboard.data(forType: kind.pasteboardType), !d.isEmpty {
                    parts[kind] = d
                }
            }
        }
        // Copied files — always captured (skip folders; needs zipping), so the
        // copy lands in history / the shareable snapshot even when automatic
        // file sync is off. Whether the content auto-broadcasts is the
        // engine's decision (config.syncFiles), not a capture concern.
        var files: [ClipFile] = []
        if isFileCopy {
            let used = parts.values.reduce(0) { $0 + $1.count }
            files = ClipboardWatcher.collectFiles(fileURLs, maxBytes: maxBytes, initialUsed: used)
        }

        guard !parts.isEmpty || !files.isEmpty else { return }

        // Size policy: if over the cap, fall back to text-only; else skip.
        var snapshot = ClipSnapshot(parts: parts, files: files)
        if snapshot.totalBytes > maxBytes {
            if let t = parts[.text], t.count <= maxBytes {
                snapshot = ClipSnapshot(parts: [.text: t])
            } else {
                Log.trace("clip", "copy over cap (\(snapshot.totalBytes)B) — skipped")
                return
            }
        }

        // Drop mixed snapshots if another app changed the pasteboard while we were
        // reading; the next poll will inspect the new types before reading data.
        guard pasteboard.changeCount == observedChange else { return }
        onLocalCopy?(snapshot, snapshot.hash)
    }

    /// Apply remote content locally (all representations), suppressing the echo
    /// it would otherwise trigger by advancing our baseline changeCount.
    /// Returns the on-disk URLs of any materialized files (empty for non-file).
    @discardableResult
    func write(_ snapshot: ClipSnapshot) -> [URL] {
        let urls = put(snapshot)
        lastChangeCount = pasteboard.changeCount   // echo-suppress
        return urls
    }

    /// Re-apply a snapshot as if freshly copied here — does NOT echo-suppress,
    /// so the watcher re-detects it and re-syncs (used for history re-apply).
    /// Returns the on-disk URLs of any materialized files (empty for non-file
    /// clips) so the caller can open them.
    @discardableResult
    func repost(_ snapshot: ClipSnapshot) -> [URL] {
        put(snapshot)
    }

    /// Writes the snapshot to the pasteboard. For file clips, materializes the
    /// files to disk, puts their URLs on the pasteboard, and returns those URLs.
    @discardableResult
    private func put(_ snapshot: ClipSnapshot) -> [URL] {
        pasteboard.clearContents()
        if !snapshot.files.isEmpty {
            // Materialize received files to disk and put file URLs on the
            // pasteboard so paste works in Finder and apps.
            let urls = writeReceivedFiles(snapshot)
            if !urls.isEmpty { pasteboard.writeObjects(urls as [NSURL]) }
            return urls
        }
        for (kind, data) in snapshot.parts {
            if kind == .text, let s = String(data: data, encoding: .utf8) {
                pasteboard.setString(s, forType: .string)
            } else {
                pasteboard.setData(data, forType: kind.pasteboardType)
            }
        }
        return []
    }

    /// Write received files under Application Support and return their URLs.
    private func writeReceivedFiles(_ snapshot: ClipSnapshot) -> [URL] {
        let fm = FileManager.default
        guard let support = fm.urls(for: .applicationSupportDirectory, in: .userDomainMask).first
        else { return [] }
        let dir = support
            .appendingPathComponent("TandemClip/Received/\(snapshot.hash.prefix(12))", isDirectory: true)
        try? fm.createDirectory(at: dir, withIntermediateDirectories: true)
        try? fm.setAttributes([.posixPermissions: 0o700], ofItemAtPath: dir.path)
        var urls: [URL] = []
        for f in snapshot.files {
            // Strip any directory components (defuses "../" traversal and absolute
            // paths), then reject the pathological basenames "", ".", and ".."
            // which would otherwise resolve `dest` to the clip dir or its parent.
            let base = (f.name as NSString).lastPathComponent
            let safe = (base.isEmpty || base == "." || base == "..") ? "file" : base
            let dest = dir.appendingPathComponent(safe)
            if (try? f.data.write(to: dest, options: [.atomic])) != nil {
                try? fm.setAttributes([.posixPermissions: 0o600], ofItemAtPath: dest.path)
                markQuarantined(dest)
                urls.append(dest)
            }
        }
        // Cheap-path the cap check: keep an approximate running byte total and do
        // the full recursive size walk only when it suggests we may be over the cap
        // (or on the first write this session, when the on-disk total is unknown).
        // The walk recomputes the authoritative total, so the accumulator
        // self-corrects and never drifts unbounded.
        let root = support.appendingPathComponent("TandemClip/Received", isDirectory: true)
        let written = urls.isEmpty ? 0 : snapshot.files.reduce(0) { $0 + $1.data.count }
        if let current = receivedCacheBytes, current + written <= receivedCacheCap {
            receivedCacheBytes = current + written
        } else {
            receivedCacheBytes = pruneReceivedCache(root: root)
        }
        return urls
    }

    /// Cap the on-disk received-file cache: evict oldest clip folders until the
    /// total is under `receivedCacheCap`. Without this the cache grows unbounded
    /// (a peer could stream large files to fill the disk); it's otherwise only
    /// cleared on "Clear history."
    private let receivedCacheCap = 200_000_000   // 200 MB
    private var receivedCacheBytes: Int?         // approx running total; nil until first measured this session

    /// Walk the received-file cache, evict oldest clip folders until under the
    /// cap, and return the resulting true byte total. Authoritative but O(all
    /// files) — callers gate it behind the cheap running-total check above.
    @discardableResult
    private func pruneReceivedCache(root: URL) -> Int {
        let fm = FileManager.default
        guard let entries = try? fm.contentsOfDirectory(
            at: root, includingPropertiesForKeys: [.contentModificationDateKey], options: []) else { return 0 }
        func dirSize(_ url: URL) -> Int {
            guard let e = fm.enumerator(at: url, includingPropertiesForKeys: [.fileSizeKey]) else { return 0 }
            var total = 0
            for case let f as URL in e { total += (try? f.resourceValues(forKeys: [.fileSizeKey]).fileSize) ?? 0 }
            return total
        }
        var dirs = entries.map { (url: $0,
                                  date: (try? $0.resourceValues(forKeys: [.contentModificationDateKey]).contentModificationDate) ?? .distantPast,
                                  size: dirSize($0)) }
        var total = dirs.reduce(0) { $0 + $1.size }
        guard total > receivedCacheCap else { return total }
        dirs.sort { $0.date < $1.date }   // oldest first
        for d in dirs where total > receivedCacheCap {
            if (try? fm.removeItem(at: d.url)) != nil {
                total -= d.size
                Log.trace("clip", "evicted received cache \(d.url.lastPathComponent)")
            }
        }
        return total
    }

    private func markQuarantined(_ url: URL) {
        let value = "0081;00000000;TandemClip;\0"
        value.withCString { ptr in
            _ = setxattr(url.path, "com.apple.quarantine", ptr, strlen(ptr), 0, 0)
        }
    }

    /// Read file URLs into `ClipFile`s (transfer-by-content), skipping folders and
    /// anything that would push the running byte total past `maxBytes`. Sizes are
    /// read from metadata *before* the bytes, so an oversize file is rejected
    /// without ever being slurped into memory. Shared by clipboard capture (poll)
    /// and drag-to-send (SyncEngine.shareFiles). `initialUsed` seeds the total
    /// with bytes already accounted for (e.g. accompanying text on a copy).
    static func collectFiles(_ urls: [URL], maxBytes: Int, initialUsed: Int = 0) -> [ClipFile] {
        var used = initialUsed
        var files: [ClipFile] = []
        for url in urls where url.isFileURL {
            var isDir: ObjCBool = false
            FileManager.default.fileExists(atPath: url.path, isDirectory: &isDir)
            if isDir.boolValue { continue }
            let size = (try? url.resourceValues(forKeys: [.fileSizeKey]).fileSize) ?? Int.max
            if used + size > maxBytes {
                Log.trace("clip", "file \(url.lastPathComponent) (\(size)B) over cap — skipped")
                continue
            }
            guard let data = try? Data(contentsOf: url) else { continue }
            used += data.count
            files.append(ClipFile(name: url.lastPathComponent, data: data))
        }
        return files
    }

    static func hash(_ data: Data) -> String {
        SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }
}
