import AppKit
import CryptoKit

/// Watches the local pasteboard and reports new *local* copies.
///
/// macOS has no clipboard-change notification, so this polls `changeCount` on a
/// timer. Key safety behaviors:
///  - Reads `types` (metadata) before reading the data, so it can skip
///    concealed/transient content without ever pulling the secret out.
///  - Honors the nspasteboard.org convention that password managers use to mark
///    secrets as un-syncable.
///  - `write(_:)` records the resulting changeCount so applying a *remote* clip
///    doesn't bounce back out as a new local copy (echo-loop prevention).
final class ClipboardWatcher {
    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?

    /// Pasteboard markers we must never sync. Set by password managers
    /// (ConcealedType), one-time/ephemeral content (TransientType), and
    /// auto-generated content. Convention: https://nspasteboard.org
    private let skipTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    var onLocalCopy: ((_ snapshot: ClipSnapshot, _ hash: String) -> Void)?
    var maxBytes: Int = 5_000_000
    var isPaused: () -> Bool = { false }
    /// Which representations to capture (text is always included).
    var enabledKinds: () -> Set<ClipKind> = { Set(ClipKind.allCases) }
    /// Whether to capture/transfer copied files by content.
    var syncFiles: () -> Bool = { false }

    init() {
        lastChangeCount = pasteboard.changeCount
    }

    func start() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.4, repeats: true) { [weak self] _ in
            self?.poll()
        }
    }

    private func poll() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        if isPaused() { return }

        // Inspect metadata first — do NOT read the data if it's marked secret.
        let typeNames = Set((pasteboard.types ?? []).map { $0.rawValue })
        if !skipTypes.isDisjoint(with: typeNames) { return }

        let kinds = enabledKinds().union([.text])   // text always considered
        var parts: [ClipKind: Data] = [:]
        for kind in kinds {
            if kind == .text {
                if let s = pasteboard.string(forType: .string), !s.isEmpty {
                    parts[.text] = Data(s.utf8)
                }
            } else if let d = pasteboard.data(forType: kind.pasteboardType), !d.isEmpty {
                parts[kind] = d
            }
        }
        // Copied files — transfer by content (skip folders; needs zipping).
        var files: [ClipFile] = []
        if syncFiles() {
            let urls = (pasteboard.readObjects(forClasses: [NSURL.self],
                        options: [.urlReadingFileURLsOnly: true]) as? [URL]) ?? []
            var used = parts.values.reduce(0) { $0 + $1.count }
            for url in urls where url.isFileURL {
                var isDir: ObjCBool = false
                FileManager.default.fileExists(atPath: url.path, isDirectory: &isDir)
                if isDir.boolValue { continue }
                guard let data = try? Data(contentsOf: url) else { continue }
                if used + data.count > maxBytes {
                    Log.trace("clip", "file \(url.lastPathComponent) over cap — skipped")
                    continue
                }
                used += data.count
                files.append(ClipFile(name: url.lastPathComponent, data: data))
            }
        }

        guard !parts.isEmpty || !files.isEmpty else { return }

        // Size policy: if over the cap, fall back to text-only; else skip.
        var snapshot = ClipSnapshot(parts: parts, files: files)
        if snapshot.totalBytes > maxBytes {
            if let t = parts[.text], t.count <= maxBytes {
                snapshot = ClipSnapshot(parts: [.text: t])
            } else {
                Log.trace("clip", "copy over cap (\(snapshot.totalBytes)B) — skipped")
                return
            }
        }

        onLocalCopy?(snapshot, snapshot.hash)
    }

    /// Apply remote content locally (all representations), suppressing the echo
    /// it would otherwise trigger by advancing our baseline changeCount.
    /// Returns the on-disk URLs of any materialized files (empty for non-file).
    @discardableResult
    func write(_ snapshot: ClipSnapshot) -> [URL] {
        let urls = put(snapshot)
        lastChangeCount = pasteboard.changeCount   // echo-suppress
        return urls
    }

    /// Re-apply a snapshot as if freshly copied here — does NOT echo-suppress,
    /// so the watcher re-detects it and re-syncs (used for history re-apply).
    /// Returns the on-disk URLs of any materialized files (empty for non-file
    /// clips) so the caller can open them.
    @discardableResult
    func repost(_ snapshot: ClipSnapshot) -> [URL] {
        put(snapshot)
    }

    /// Writes the snapshot to the pasteboard. For file clips, materializes the
    /// files to disk, puts their URLs on the pasteboard, and returns those URLs.
    @discardableResult
    private func put(_ snapshot: ClipSnapshot) -> [URL] {
        pasteboard.clearContents()
        if !snapshot.files.isEmpty {
            // Materialize received files to disk and put file URLs on the
            // pasteboard so paste works in Finder and apps.
            let urls = writeReceivedFiles(snapshot)
            if !urls.isEmpty { pasteboard.writeObjects(urls as [NSURL]) }
            return urls
        }
        for (kind, data) in snapshot.parts {
            if kind == .text, let s = String(data: data, encoding: .utf8) {
                pasteboard.setString(s, forType: .string)
            } else {
                pasteboard.setData(data, forType: kind.pasteboardType)
            }
        }
        return []
    }

    /// Write received files under Application Support and return their URLs.
    private func writeReceivedFiles(_ snapshot: ClipSnapshot) -> [URL] {
        let fm = FileManager.default
        guard let support = fm.urls(for: .applicationSupportDirectory, in: .userDomainMask).first
        else { return [] }
        let dir = support
            .appendingPathComponent("TandemClip/Received/\(snapshot.hash.prefix(12))", isDirectory: true)
        try? fm.createDirectory(at: dir, withIntermediateDirectories: true)
        var urls: [URL] = []
        for f in snapshot.files {
            let safe = (f.name as NSString).lastPathComponent
            let dest = dir.appendingPathComponent(safe.isEmpty ? "file" : safe)
            if (try? f.data.write(to: dest)) != nil { urls.append(dest) }
        }
        return urls
    }

    static func hash(_ data: Data) -> String {
        SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }
}
