import AppKit
import CryptoKit

/// Watches the local pasteboard and reports new *local* copies.
///
/// macOS has no clipboard-change notification, so this polls `changeCount` on a
/// timer. Key safety behaviors:
///  - Reads `types` (metadata) before reading the actual string, so it can skip
///    concealed/transient content without ever pulling the secret out.
///  - Honors the nspasteboard.org convention that password managers use to mark
///    secrets as un-syncable.
///  - `write(_:)` records the resulting changeCount so applying a *remote* clip
///    doesn't bounce back out as a new local copy (echo-loop prevention).
final class ClipboardWatcher {
    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?

    /// Pasteboard markers we must never sync. Set by password managers
    /// (ConcealedType), one-time/ephemeral content (TransientType), and
    /// auto-generated content. Convention: https://nspasteboard.org
    private let skipTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    var onLocalCopy: ((_ text: String, _ hash: String) -> Void)?
    var maxBytes: Int = 1_000_000
    var isPaused: () -> Bool = { false }

    init() {
        lastChangeCount = pasteboard.changeCount
    }

    func start() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.4, repeats: true) { [weak self] _ in
            self?.poll()
        }
    }

    private func poll() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        if isPaused() { return }

        // Inspect metadata first — do NOT read the data if it's marked secret.
        let typeNames = Set((pasteboard.types ?? []).map { $0.rawValue })
        if !skipTypes.isDisjoint(with: typeNames) { return }

        guard let str = pasteboard.string(forType: .string), !str.isEmpty else { return }

        let data = Data(str.utf8)
        if data.count > maxBytes { return }

        onLocalCopy?(str, ClipboardWatcher.hash(data))
    }

    /// Apply remote content locally, suppressing the echo it would otherwise
    /// trigger by advancing our baseline changeCount past this write.
    func write(_ text: String) {
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
        lastChangeCount = pasteboard.changeCount
    }

    static func hash(_ data: Data) -> String {
        SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }
}
